### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/go-weather#8]
## Feature Description

Update ReadMe file to include full details about client. Also add EXAMPLES.md for examples about each available function.

---

## Use Case

N/A

---

## Proposed Solution

N/A

---

## Additional Context

N/A

---

## Pseudo Code

```go
// Provide a code snippet or example that demonstrates how this feature might be used

**Comment by that-ar-guy** [comment]
Hey @kashifkhan0771  can i take this issue

**Comment by kashifkhan0771** [comment]
Sure @that-ar-guy I am assigning this to you. Thank you!
